query_name: ibd_dda_cd 
query_sigs: /home/ntpierce/2022-magsearch-tr/ibd_dda_cd.siglist.txt
wort_sigs: /group/ctbrowngrp/irber/data/wort-data/wort-sra/sigs
s3_dir: outputs/wort-sra/sigs
threshold: 0.01
ksize: 31
out_dir: "output.magsearch"
